### ISSUE TITLE
Missing required prop: "token" 

### ISSUE THREAD

**Issue by taylorkrause** [docusealco/docuseal-vue#1]
Hey all.. trying to use the vue docuseal builder but keep running into this issue. The required prop is definitely not missing. Any ideas?

**Comment by omohokcoj** [comment]
@taylorkrause are you using Vue2 or Vue3 ? This package works only with Vue3

**Comment by taylorkrause** [comment]
Oh shit that makes so much sense. Thanks @omohokcoj !!!

**Comment by omohokcoj** [comment]
@taylorkrause for Vue2 just using a javascript web element should be sufficient: 
https://www.docuseal.co/docs/embedded/form

**Comment by taylorkrause** [comment]
sounds good brother!!!
